use crate::func::Commands::Say;
use crate::func::{Commands, FuncFile};

pub fn create_function(data: FuncFile) -> (String, String) {
    let name = data.name;
    let raw = create_function_vec(data.data);
    (name, raw)
}

pub fn create_function_vec(data: Vec<Commands>) -> String {
    let mut raw = String::new();
    let auto_gen = r##"## <auto-generated by="dotmc">
## このファンクションは、"dotmc" によって生成されたものです。変更しないでください。
## This function is generated by "dotmc". Do not change.
## </auto-generated>"##;

    raw = auto_gen.to_string();

    //todo: コマンドの追加
    for command in data {
        match command {
            Say(s) => {
                let com = format!("say {}", s);
                raw = format!("{}\n{}", raw, com);
            }
            _ => panic!("コマンドが登録されていません"),
        }
    }

    raw
}

#[test]
fn say_test() {
    let func = FuncFile::new(
        "test".to_string(),
        vec![Say("hello".to_string()), Say("hello2".to_string())],
    );
    let (name, data) = create_function(func);

    println!("name:{},data:{}", name, data)
}

#[test]
fn vec_test() {
    let vec = vec![Say("hello".to_string()), Say("hello2".to_string())];
    let re = create_function_vec(vec);
    println!("data:{}", re)
}

#[test]
fn test() {
    println!(r###"{{"values":[""###)
}

/*
## <auto-generated by="dotmc">
## このファンクションは、"dotmc" によって生成されたものです。変更しないでください。
## This function is generated by "dotmc". Do not change.
## </auto-generated>t
*/
